version: '3'

services:
  hw017-app:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    image: hw017-spring-zaremba:1.0
    container_name: hw017-app
#    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8080:8099"
    # Эти свойства перегружают соответствующие в application.yml
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/demoDB
      SPRING_DATASOURCE_USERNAME: usr
      SPRING_DATASOURCE_PASSWORD: pwd

  postgres:
    image: "postgres:12"
    container_name: postgres
#    restart: unless-stopped
    ports:
      - "5432:5430"
    environment:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: demoDB
