spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demoDB
    username: usr
    password: pwd
    driver-class-name: org.postgresql.Driver

  sql:
    init:
#      mode: never
      mode: always
#      data-locations: data.sql
#      schema-locations: schema.sql

  jpa:
    generate-ddl: false
#    generate-ddl: true
    hibernate:
      ddl-auto: none
#      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
#        format_sql: true

  jmx:
    enabled: true

logging:
  level:
    root: INFO
  file:
    name: "logs/application.log"
  pattern:
    file: "%date %level [%thread] [%file:%line] %msg%n"

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "metrics,health,logfile,prometheus"
  endpoint:
    metrics:
      enabled: true
    health:
      enabled: true
      show-components: always
      show-details: when-authorized
      roles: "ADMIN"
    logfile:
      enabled: true
    prometheus:
      enabled: true

server:
  port: 8099