spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hw008Mongo

  shell:
    interactive:
      enabled: true
      #enabled: false
#  main:
#    allow-circular-references: true

mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.homework.changelogs

logging:
  level:
    root: ERROR
