server:
  port: 8080

spring:
  application:
    name: feign-client-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

logging:
  level:
    root: ERROR

diff-postfix: "_from library service"

hystrix:
  command:
    default:
      isolation:
        thread:
          timeoutInMilliseconds: 3000

management:
  endpoints:
    web:
      exposure:
        include: "*"
