spring:
  data:
    mongodb:
      database: hw011ReactiveMongo
      host: localhost
      port: 27017

mongock:
  #  runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.homework.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
    root: ERROR