spring:
  messages:
    basename: "appmessages"
    encoding: "UTF-8"
#  main:
#    allow-circular-references: true

app:
  properties:
    csv-resource-name: "questions.csv"
    score-to-pass: 4
    locale: ru_RU

logging:
  level:
    root: ERROR