server:
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://awseb-e-2iftjefsdi-stack-awsebrdsdatabase-kxyhc5ri3qxq.cqvpgdadnfro.eu-north-1.rds.amazonaws.com:3306/ebdb
    username: usr
    password: password
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    root: INFO
